name: Tests
on: [push]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: touch /github/workspace/database/database.sqlite
      - uses: nathanheffley/laravel-phpunit-action@master
